node {
  def mavenTool = tool 'maven-jenkins'
  try{
    stage('Preparation'){
      git branch: 'master', url: 'https://github.com/faustoobama/mavenapp.git'
    }
    stage('Build'){
      sh 'cd demo && ${mavenTool}/bin/mvn -B -DskipTests clean package'
    }
    stage('Test'){
      sh 'cd demo && ${mavenTool}/bin/mvn test'
    }

    stage('Deploy'){
      sh 'java -jar demo/target/demo-1.jar'
    }
  }catch(Exception e){
    echo "Pipeline failled: ${e.message}"
    currentBuild.result = 'FAILURE'
  }finally{
    cleanWs()
  }
}
