node {
  def mavenTool = tool 'maven_jenkins'
  try{
    stage('Preparation'){
      git branch: 'master', url: 'https://github.com/faustoobama/mavenapp.git'
    }
    stage('Build'){
      sh '''
      echo "Starting Build stage"
        cd demo &&
        ${mavenTool}/bin/mvn -B -DskipTests clean package
      '''
    }
    
    stage('Test'){
      sh '''
      echo "Starting testing stage"
        cd demo &&
        ${mavenTool}/bin/mvn test
      '''
    }

    stage('Deploy'){
      sh '''
        echo "Deploying ..."
        java -jar demo/target/demo-1.jar
      '''
    }
  }catch(Exception e){
    echo "Pipeline failled: ${e.message}"
    currentBuild.result = 'FAILURE'
  }finally{
    cleanWs()
  }
}
